### ISSUE TITLE
LVGL 9.0 issue

### ISSUE THREAD

**Issue by mtibi75** [mdaskalov/AnalogClock#1]
Hello!
Really nice project, I tried it in Tasmota v13.2.0.
However, after I updated to Tasmota v13.4.0 I get an error message:
BRY: failed to run compiled code 'attribute_error' - module 'lv' has no member 'IMG_CF_TRUE_COLOR_ALPHA'
stack traceback:
	:22: in function `init`
	:35: in function `init`
	<unknown source>: in function `main`
	<unknown source>: in function `try_run_compiled`
	<unknown source>: in function `load`
	:1: in function `load`
The cause of the problem may be that the LVGL library has been updated:
"ESP32 LVGL library from v8.3.11 to v9.0.0, some small breaking changes in C, none in HASPmota https://github.com/arendst/Tasmota/issues/20659"
Can you fix the error?
Thx, mtibi75

**Comment by mdaskalov** [comment]
I know...
I have to rewrite it for LVGL 9.0 using layers. Need some more time, be patient.

**Comment by mdaskalov** [comment]
...finally found a way to fix it using LVGL v9.0 (download the latest release).
